[tool.black]
line-length = 79
target-version = ['py310']

[tool.isort]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
python_version = "3.10"

[[tool.mypy.overrides]]
module = ["matplotlib","matplotlib.pyplot"]
ignore_missing_imports = true
