from collections import OrderedDict

y_to_name = OrderedDict(
    [
        (0, "Alef"),
        (1, "Ayin"),
        (2, "Bet"),
        (3, "Dalet"),
        (4, "Gimel"),
        (5, "He"),
        (6, "Het"),
        (7, "Kaf"),
        (8, "Kaf-final"),
        (9, "Lamed"),
        (10, "Mem"),
        (11, "Mem-medial"),
        (12, "Nun-final"),
        (13, "Nun-medial"),
        (14, "Pe"),
        (15, "Pe-final"),
        (16, "Qof"),
        (17, "Resh"),
        (18, "Samekh"),
        (19, "Shin"),
        (20, "Taw"),
        (21, "Tet"),
        (22, "Tsadi-final"),
        (23, "Tsadi-medial"),
        (24, "Waw"),
        (25, "Yod"),
        (26, "Zayin"),
    ]
)

y_to_unicode = OrderedDict(
    [
        (0, "א"),
        (1, "ע"),
        (2, "ב"),
        (3, "ד"),
        (4, "ג"),
        (5, "ה"),
        (6, "ח"),
        (7, "כ"),
        (8, "ך"),
        (9, "ל"),
        (10, "ם"),
        (11, "מ"),
        (12, "ן"),
        (13, "נ"),
        (14, "פ"),
        (15, "ף"),
        (16, "ק"),
        (17, "ר"),
        (18, "ס"),
        (19, "ש"),
        (20, "ת"),
        (21, "ט"),
        (22, "ץ"),
        (23, "צ"),
        (24, "ו"),
        (25, "י"),
        (26, "ז"),
    ]
)

name_to_unicode = OrderedDict(
    [
        ("Alef", "א"),
        ("Ayin", "ע"),
        ("Bet", "ב"),
        ("Dalet", "ד"),
        ("Gimel", "ג"),
        ("Het", "ח"),
        ("He", "ה"),
        ("Kaf-final", "ך"),
        ("Kaf", "כ"),
        ("Lamed", "ל"),
        ("Mem-medial", "מ"),
        ("Mem", "ם"),
        ("Nun-final", "ן"),
        ("Nun-medial", "נ"),
        ("Pe-final", "ף"),
        ("Pe", "פ"),
        ("Qof", "ק"),
        ("Resh", "ר"),
        ("Samekh", "ס"),
        ("Shin", "ש"),
        ("Taw", "ת"),
        ("Tet", "ט"),
        ("Tsadi-final", "ץ"),
        ("Tsadi-medial", "צ"),
        ("Waw", "ו"),
        ("Yod", "י"),
        ("Zayin", "ז"),
    ]
)
